server.host: "0.0.0.0"
server.name: "soc-kibana"
elasticsearch.hosts: ["http://elasticsearch:9200"]
monitoring.ui.container.elasticsearch.enabled: true
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "soc-platform-secret-key-32chars!!"
logging:
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json
  root:
    appenders: [default, file]